# 1.SpringBoot配置

spring:
  application:
    name: ccait.ccweb #服务名
  datasource:
    druid:
      test-on-borrow: true
      test-while-idle: true

  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

  zipkin: #分布式链路配置
    base-url: http://localhost:9411
  thymeleaf:
    cache: false
  devtools: #dev tools
    livereload:
      enabled: true
  session:
    store-type: none # none, redis, mongo
    cookie:
      max-age: 43200000
    persistent: false

  mvc:
    async:
      request-timeout: 5000
    static-path-pattern: /** #静态文件请求匹配方式
  resources: #修改默认的静态寻址资源目录
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


# 2.SpringCloud配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9005/eureka/ #注册中心
  instance:
    instance-id: ccweb-auth:8000

feign:
  hystrix:
    enabled: true


# 3.log4j配置
log4j:
  config:
    path: log4j2.xml #日志配置路径，可选
  logger:
    org:
      springframework:
        cloud: OFF


# 4.websocket配置
websocket:
  server: 127.0.0.1
  enable: true
  protocol: ws
  port: 8000


# 5.MQTT服务配置
mqtt:
  server:
    host: 127.0.0.1
    port: 1999
    ssl: false
    log: true
  client:
    host: tcp://127.0.0.1:1999 #逗号分隔
    clientId: ccait_client_id
    enableClientRandom: true
    username: testtt
    password: testtt
    timeout: 10000
    keepalive: 20
    retain: true
    charset: UTF-8
    subscribe:
      topic-list:
        - testtt:
            qos: 0

# 6.ccweb配置
entity:
  lang: cn
  datasource:
    activated: sqlite #可通过url的{datasource}参数访问到该数据库，没有在此设置的environment不能通过url访问到
    #configFile: db-config.xml #数据库配置路径
    environments:
      sqlite:
        default: true
        driver: org.sqlite.JDBC
        url: jdbc:sqlite:ccait.db

  ignoreTotalCount: true #忽略查询总数
  package: ccait.ccweb.entites #实体类生成包路径
  suffix: Entity #实体类生成类名后辍
  page: #分页配置选项
    maxSize: 50 #分页最大记录数默认值
  defaultDateByNow: false
  auth:
    user:
      jwt:
        millis: 600000
        enable: true
      aes:
        enable: true
      wechat:
        appid: openid4sa411f32sd1f1sa
        secret: tokenfd53sa411f32sd1f1sa
        enable: true
    service:
      server:
        enable: true
        instances: ccweb-auth:8000 #逗号分隔
        publicKey: ccait.cn
      client:
        privateKey: ccweb

  security: #安全配置选项
    encrypt:
      MD5: #MD5加密配置
        fields: user.password #需要使用MD5加密的字段，逗号分隔
        publicKey: ccait@2020 #MD5加密公钥
      AES: #AES加密配置
        publicKey: ccait@2020 #AES加密公钥
    admin: #超级管理员账号密码(必填)
      username: admin
      password: admin

  validation: #数据提交字段校验器，以下email、mobile为字段名，也可以精确校验:[表名].[字段名]
    email:
      match: ^[A-Za-z0-9\u4e00-\u9fa5]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$
      message: 请输入正确的电子邮箱格式
    mobile:
      match: ^((13[0-9])|(14[5,7])|(15[0-3,5-9])|(17[0,3,5-8])|(18[0-9])|166|198|199|(147))\\d{8}$
      message: 请输入正确的手机号码

  formatter: #查询结果输出格式，createOn、modifyOn，也可以精确格式化:[表名].[字段名]
    createOn: yyyy-MM-dd HH:mm
    modifyOn: yyyy-MM-dd HH:mm
    start_time: yyyy-MM-dd HH:mm
    end_time: yyyy-MM-dd HH:mm
    startTime: yyyy-MM-dd HH:mm
    endTime: yyyy-MM-dd HH:mm
    evaluateTime: yyyy-MM-dd HH:mm
    appraise_time: yyyy-MM-dd HH:mm

  table:
    reservedField: #系统保留字段(必填)
      userPath: userPath #创建者所属路径，体现父子关系，用于like查询
      createOn: createOn #数据创建时间
      createBy: createBy #数据创建者
      modifyOn: modifyOn #数据修改时间
      groupId: groupId  #群组ID
      roleId: roleId #角色ID
      aclId: roleId #访问控制ID
      privilegeId: privilegeId #权限ID
      userGroupRoleId: userGroupRoleId #用户组角色关联ID
      userId: userId #用户ID(整型，会被计算到userPath中)
      id: id #系统默认id字段名

    #系统保留表(必填)
    user: user #用户表
    group: group #分组表
    role: role #角色表
    acl: acl #访问控制表
    privilege: privilege #操作权限表
    userGroupRole: userGroupRole #用户/组/角色关联关系

    display: #需要隐藏的字段，设为hidden的字段不会在查询结果中显示
      user:
        password: hidden

  upload: #上传设置
    multiple: true
    workerlib: #库名
      alluser: #表名
        qr_code: #字段名
          maxSize: 5 #上传文件最大尺寸，单位: MB
          mimeType: gif, jpg, png, jpeg #允许上传的文件格式
          path: /home/upload/qrcode
        photo: #字段名
          maxSize: 5 #上传文件最大尺寸，单位: MB
          mimeType: gif, jpg, png, jpeg #允许上传的文件格式
          path: /home/upload #上传路径的绝对路径


  download: #下载设置
    thumb:  #预览的缩略图
      fixedWidth: 200 #固定宽度
      scalRatio: 50 #缩放比率(百分比)
      watermark: watermark.png #水印

  redis:
    enable: false
    cluster: false
    # nodes: 127.0.0.1:8667
    host: 127.0.0.1
    port: 6379
    timeout: 0

  #  ip:
  #    whiteList:  #IP白名单
  #    blackList:  #IP黑名单

  elasticSearch:
    enable: false
    timeout: 10000
    cluster-name: 127.0.0.1:9200 #逗号分隔
    indexs: #索引设置
      user_username: user.username #key＝indexname, value=[{tablename}].{fieldname}
    highlight: #高亮设置
      user: #表名
        fields: username #字段名，逗号分隔
        fragmentSize: 200
        preTags: <em>
        postTags: </em>
        script: painless
        painless:
          password: "doc['password']=\"*****\"; return doc['password'];"


  defaultValue: #指定表字段为null时赋于默认值，UUID_RANDOM=UUID.randomUUID()，DATE_NOW=Datetime.now()
    userGroupRoleId: UUID_RANDOM
    role.roleId: UUID_RANDOM
    group.groupId: UUID_RANDOM
    privilegeId: UUID_RANDOM
    acl.aclId: UUID_RANDOM

# 7.服务器配置
server:
  port: 8000 #端口号
  tomcat:
    max-threads: 500000
  servlet:
    session:
      timeout: 86000

